### ISSUE TITLE
配置文件在哪？

### ISSUE THREAD

**Issue by wpzzz** [kirin10000/V2Ray-WebSocket-TLS-Web-setup-script#5]
你好，上两天安装了一次，安装完成之后发现没有/etc/v2ray这个文件夹，通过systemctl status v2ray 看到配置文件是 /usr/local/etc/v2ray/config.json  ，但是打开这个文件 里面只有两个括号

**Comment by kirin10000** [comment]
主要是因为大概半个月前v2ray官方的一键安装脚本更新
https://github.com/v2fly/fhs-install-v2ray
从/etc/v2ray变成了/usr/local/etc/v2ray

然后13天前又更新了一次，配置文件的位置又变了。。。
https://github.com/v2fly/fhs-install-v2ray/commit/0b4c092a5464998c93678070e3808196596638b7

现在脚本已经更新，你下载最新的安装脚本，重新安装一遍就能运行了
配置文件位置为/usr/local/etc/v2ray/config.json。

**Comment by kirin10000** [comment]
配置文件变来变去的我也很难受，希望官方不要再变了😂
