### ISSUE TITLE
部署成功后 Twitter iOS 客户端无法打开 其他用户的 profile page

### ISSUE THREAD

**Issue by realfisher** [kirin10000/V2Ray-WebSocket-TLS-Web-setup-script#6]
Twitter iOS 客户端 从timeline 点开 其他用户的 profile page时，无法获取数据，显示用户不存在。但可以通过搜索用户的方式访问profile page。除此之外的功能完全正常。其他网站/应用也未发现问题。VPS部署在aws，尝试了lightsail 和ec2，均有此问题，Vless 和 Vmess均受影响；未使用 CDN。客户端也在墙外，所以可以排除墙的影响。
![IMG_8437](https://user-images.githubusercontent.com/71288647/93129197-a1521c00-f69e-11ea-9733-8f0f71f80202.PNG)

**Comment by kirin10000** [comment]
初步判断应该是服务器的问题，服务器无法访问Twitter的profile page。 可以尝试更换服务器dns。

**Comment by realfisher** [comment]
谢谢回复。不知道您说的  更换服务器 dns 指的是什么。更换DNS 提供商嘛？现在 服务器 的A record是放在 Route 53的。
当使用电脑连接vps，通过浏览器访问Twitter时，没有此问题，所以有些困惑。

**Comment by realfisher** [comment]
尝试了script里更新dns的选项，依旧没有解决问题。查看了nginx 和 v2ray的log，也没有什么头绪。我再多试试吧。先close，如果找到原因，再来comment。谢谢啦。
